eureka:
  instance:
    hostname: eurekaThird
  client:
    service-url:
      #完成3个server服务间的相互注册
      defaultZone: http://eurekaSecond:8761/eureka/,http://eurekaFirst:8761/eureka/
    #表示是否注册自身到eureka服务器
    register-with-eureka: true
    #是否从eureka上获取注册信息
    fetch-registry: true
  server:
    enable-self-preservation: false  #开发环境关闭自我保护机制
spring:
  application:
    name: eureka
management:
  server:
    servlet:
      context-path: /
